#!/bin/bash -xe

git clone https://github.com/kfox1111/hubbuildtools

hubbuildtools/hubhookhelpers/quinesetup

PROVISION_K8S_VERSION=$(hubbuildtools/hubcurlrevision.sh kfox1111/provision-k8s-server centos7-latest)
K8S_BASE_VERSION=$(echo $PROVISION_K8S_VERSION | sed 's/-[0-9]*$//')

REPOREVISION=$K8S_BASE_VERSION
K8S_VERSION=v$K8S_BASE_VERSION

ETCD_VERSION=3.0.17
PAUSE_VERSION=3.0
KUBE_DNS_VERSION=1.14.5
CALICO_NODE_VERSION=v2.6.2
CALICO_CNI_VERSION=v1.11.0
FLANNEL_VERSION=v0.9.1

function repo2repo {
  docker pull $REPO/"$1":"$2"
  docker tag $REPO/"$1":"$2" localhost:5000/k8s-$REPOREVISION/"$1":"$2"
  docker push localhost:5000/k8s-$REPOREVISION/"$1":"$2"
}

export REPO=gcr.io/google-containers

repo2repo etcd-amd64 $ETCD_VERSION

repo2repo kube-proxy-amd64 $K8S_VERSION
repo2repo kube-apiserver-amd64 $K8S_VERSION
repo2repo kube-controller-manager-amd64 $K8S_VERSION
repo2repo kube-scheduler-amd64 $K8S_VERSION
repo2repo pause-amd64 $PAUSE_VERSION
repo2repo k8s-dns-kube-dns-amd64 $KUBE_DNS_VERSION
repo2repo k8s-dns-dnsmasq-nanny-amd64 $KUBE_DNS_VERSION
repo2repo k8s-dns-sidecar-amd64 $KUBE_DNS_VERSION

export REPO=quay.io
repo2repo calico/node $CALICO_NODE_VERSION
repo2repo calico/cni $CALICO_CNI_VERSION
repo2repo coreos/flannel $FLANNEL_VERSION

export REPO=kfox1111
repo2repo provision-k8s-server $PROVISION_K8S_VERSION

hubbuildtools/hubhookhelpers/quinebuild
